
MyApp\Component\Product\Domain\Owner:
  type: entity
  #repositoryClass: MyApp\Bundle\ProductBundle\Owner\Repository\MySqlOwnerRepository
  table: owner
  id:
      id:
          type: integer
          generator: { strategy: AUTO }
  fields:
       name:
          type: string
          length: 100
          unique: true