
MyApp\Component\Product\Domain\Product:
  type: entity
  table: product
  id:
      id:
          type: integer
          generator: { strategy: AUTO }
  fields:
       name:
          type: string
          length: 100
       price:
          type: decimal
          scale: 2
       description:
          type: text
  cascade: persist
  manyToOne:
       owner:
          targetEntity: Owner
          inversedBy: products
          joinColumn:
          name: ownerId
          referencedColumnName: id